/* Stage outputs generated from one case file. Every renderer is deterministic: it reads the case
   and the vocabulary only, so re-running without editing a case reproduces the same bytes. */
const fs = require('node:fs');
const path = require('node:path');
const V = require('./vocabulary.cjs');
const { validateCase, errorsIn, repoRoot } = require('./validate.cjs');

const outRoot = path.join(__dirname, 'out');
const cell = value => String(value ?? '').replace(/\r?\n/g, ' ').replace(/\|/g, '\\|').trim();
const list = values => (values || []).join('; ');
const csvCell = value => {
  const text = String(value ?? '').replace(/\r?\n/g, ' ');
  const guarded = /^[\s]*[=+@-]/.test(text) ? `'${text}` : text;
  return /[",]/.test(guarded) ? `"${guarded.replace(/"/g, '""')}"` : guarded;
};
const csv = rows => rows.map(row => row.map(csvCell).join(',')).join('\n') + '\n';
const money = amount => typeof amount === 'number' ? `$${amount.toLocaleString('en-US', { minimumFractionDigits: 2, maximumFractionDigits: 2 })}` : '—';

function banner(data) {
  const lines = [`Case \`${data.case.id}\` · event \`${data.event.id}\` · prepared ${data.case.prepared_on} · generated by \`pipeline/cli.cjs\`.`];
  if (data.case.inherits_from) lines.push('', `Event fact spine, sources and cost model inherited from case \`${data.case.inherits_from}\`. This case adds only the prospect side.`);
  if (data.case.illustrative === true) {
    lines.push('', '> **Illustrative case.** Every record here is a synthetic rehearsal record. It is not a researched prospect, an approach, an approval, a payment or a booking.');
  }
  return lines.join('\n');
}

function sourceLine(data, ids) {
  const byId = new Map(data.sources.map(source => [source.id, source]));
  return (ids || []).map(id => {
    const source = byId.get(id);
    return source ? `${id} (${source.locator})` : id;
  }).join('; ');
}

function governanceReport(data, findings) {
  const checks = [...new Set(findings.map(f => f.check))].sort();
  const counts = { error: errorsIn(findings).length, warning: findings.length - errorsIn(findings).length };
  const rows = findings.map(f => `| ${f.severity} | ${cell(f.check)} | ${cell(f.id)} | ${cell(f.message)} |`);
  return [
    `# Governance report — ${cell(data.case.title || data.case.id)}`, '', banner(data), '',
    `${counts.error} error(s), ${counts.warning} warning(s). Errors block rendering and CRM staging; warnings stay visible and are not silently cleared.`, '',
    '## Checks enforced', '',
    ...Object.entries({
      'case.shape': 'Required sections and a dated case header.',
      'event.scope': 'One event per case; every opportunity belongs to it.',
      'sources.integrity': 'Unique sources with a reachable repository path or an http(s) URL.',
      'evidence.tiers': 'Every record carries evidence tier 1-5 and what that tier requires.',
      'evidence.references': 'Each source_id resolves inside this case.',
      'claims.reuse': 'Only tier 1 evidence may be marked customer-safe; issued deliverables cite customer-safe facts.',
      'pricing.provisional_defaults': 'Unquoted package prices stay null and "to_be_confirmed"; internal figures stay internal.',
      'entities.layers': 'Account, unit, contact and opportunity each resolve to their parent.',
      'workflow.vectors': 'All five status vectors present with allowed values.',
      'contacts.no_guess': 'Contact details only when published on a primary page; never inferred.',
      'crm.gating': 'CRM-ready needs published detail, recorded permission and a known relationship owner.',
      'illustrative.separation': 'Fictional records are labelled and kept apart from real opportunity ids.',
      'deliverables.paths': 'Named deliverable files exist in the repository.',
      'walkthrough.moments': 'All five demonstration moments accounted for, with their artifacts present.'
    }).map(([check, description]) => `- \`${check}\` — ${description}${checks.includes(check) ? ' *(finding below)*' : ''}`), '',
    '## Findings', '',
    findings.length ? ['| Severity | Check | Record | Finding |', '|---|---|---|---|', ...rows].join('\n') : 'No findings.', ''
  ].join('\n');
}

function factSpine(data) {
  const tiers = [1, 2, 3, 4, 5];
  const sections = tiers.map(tier => {
    const facts = data.fact_spine.filter(fact => fact.tier === tier);
    const spec = V.EVIDENCE_TIERS[tier];
    const head = [`### Tier ${tier} — ${spec.label}`, '', `${spec.description}`, ''];
    if (!facts.length) return [...head, '_No facts recorded at this tier._', ''].join('\n');
    const rows = facts.map(fact => `| ${cell(fact.id)} | ${cell(fact.topic)} | ${cell(fact.statement)} | ${cell(fact.reuse)} | ${cell(sourceLine(data, fact.source_ids) || fact.basis || fact.needed_for || (fact.illustrative ? 'Illustrative record; no source' : ''))} |`);
    return [...head, '| ID | Topic | Statement | Reuse | Source / basis |', '|---|---|---|---|---|', ...rows, ''].join('\n');
  });
  const cost = data.cost_model;
  const costTable = (title, entries, note) => {
    const rows = (entries || []).map(entry => `| ${cell(entry.label)} | ${entry.quoted === false || entry.amount === null ? '_unquoted_' : money(entry.amount)} | ${entry.tier} | ${cell(entry.status || entry.reuse)} | ${cell(entry.note)} |`);
    return [`### ${title}`, '', note, '', '| Line | Amount | Tier | State | Note |', '|---|---|---|---|---|', ...(rows.length ? rows : ['| _none recorded_ | — | — | — | — |']), ''].join('\n');
  };
  return [
    `# Stage 1 — Commercial fact spine: ${cell(data.case.title || data.case.id)}`, '', banner(data), '',
    `**${cell(data.event.name)}** · ${cell(data.event.display_date || data.event.date)} · ${cell(data.event.venue)} · producer ${cell(data.event.producer)}`, '',
    ...(data.event.qualification ? [`> ${cell(data.event.qualification)}`, ''] : []),
    '## Facts by evidence tier', '', ...sections,
    '## Cost model', '',
    'Fixed event overhead, variable per-person travel cost and the customer package price are separate lines. A figure in one group is never carried into another.', '',
    costTable('Fixed event overhead', cost.fixed, 'Commitments that do not move with headcount. Internal only.'),
    costTable('Variable per person', cost.variable_per_person, 'Per-participant working figures. Internal only.'),
    costTable('Customer package', cost.customer_package, 'What a client would be quoted. Unconfirmed lines stay unquoted; no number is invented to fill a gap.'),
    '## Unknowns that gate a live action', '',
    '| ID | Missing fact | Needed before |', '|---|---|---|',
    ...data.fact_spine.filter(fact => fact.tier === 5).map(fact => `| ${cell(fact.id)} | ${cell(fact.statement)} | ${cell(fact.needed_for)} |`), ''
  ].join('\n');
}

function researchStaging(data) {
  const rows = [['layer', 'id', 'parent_id', 'name', 'detail', 'evidence_tier', 'evidence_class', 'source_urls', 'verification_date', 'crm_ready', 'hold_reason']];
  const byId = new Map(data.sources.map(source => [source.id, source]));
  const locators = ids => (ids || []).map(id => (byId.get(id) || {}).locator).filter(Boolean).join('; ');
  const checked = ids => (ids || []).map(id => (byId.get(id) || {}).checked_on).filter(Boolean).sort().pop() || '';
  const tierLabel = tier => (V.EVIDENCE_TIERS[tier] || {}).label || '';
  for (const account of data.accounts) {
    rows.push(['account', account.id, '', account.name, `${account.type || ''} · ${[account.city, account.state].filter(Boolean).join(', ')}`,
      account.tier, tierLabel(account.tier), locators(account.source_ids), checked(account.source_ids), 'false', account.relationship_status || '']);
  }
  for (const unit of data.units || []) {
    rows.push(['unit', unit.id, unit.account_id, unit.name, unit.kind || '', unit.tier, tierLabel(unit.tier), locators(unit.source_ids), checked(unit.source_ids), 'false', unit.note || '']);
  }
  for (const contact of data.contacts || []) {
    rows.push(['contact', contact.id, contact.account_id, contact.name, `${contact.role || ''} · ${contact.email || 'no published email'}`,
      contact.tier, tierLabel(contact.tier), locators(contact.source_ids), checked(contact.source_ids), String(contact.crm_ready === true),
      contact.crm_ready === true ? '' : `permission_to_contact: ${contact.permission_to_contact || 'unknown'}`]);
  }
  for (const opportunity of data.opportunities) {
    rows.push(['opportunity', opportunity.id, opportunity.account_id, opportunity.name || opportunity.id, opportunity.unit_id || '',
      opportunity.tier, tierLabel(opportunity.tier), locators(opportunity.source_ids), '', 'false', opportunity.next_action || '']);
  }
  return csv(rows);
}

function blockersFor(opportunity) {
  return Object.entries(V.STATUS_VECTORS)
    .map(([name, spec]) => ({ name, spec, value: opportunity.status_vectors[name], state: V.vectorClass(name, opportunity.status_vectors[name]) }))
    .filter(entry => entry.state === 'blocking');
}

function actionBrief(data) {
  const accounts = new Map(data.accounts.map(account => [account.id, account]));
  const roles = [...new Set(data.opportunities.map(o => o.owner_role || 'Unassigned'))].sort();
  const sections = roles.map(role => {
    const owned = data.opportunities.filter(o => (o.owner_role || 'Unassigned') === role);
    const body = owned.map(opportunity => {
      const account = accounts.get(opportunity.account_id) || {};
      const blocking = blockersFor(opportunity);
      const waiting = Object.entries(V.STATUS_VECTORS)
        .filter(([name]) => V.vectorClass(name, opportunity.status_vectors[name]) === 'in_progress')
        .map(([, spec]) => spec.label);
      const lines = [`#### ${cell(account.name || opportunity.account_id)} — ${cell(opportunity.name || opportunity.id)}`, ''];
      if (blocking.length) {
        lines.push('| Blocking dependency | Current state | What unblocks it |', '|---|---|---|',
          ...blocking.map(entry => `| ${cell(entry.spec.label)} | ${cell(entry.value)} | ${cell((opportunity.unblock || {})[entry.name] || 'Not recorded')} |`), '');
      } else {
        lines.push('No blocking dependency.', '');
      }
      if (waiting.length) lines.push(`Waiting: ${cell(waiting.join(', '))}.`, '');
      lines.push(`Next action: ${cell(opportunity.next_action || 'Not recorded')}`, '');
      return lines.join('\n');
    });
    return [`### ${cell(role)}`, '', ...body].join('\n');
  });
  const unknowns = data.fact_spine.filter(fact => fact.tier === 5);
  return [
    `# Stage 3 — Action brief: ${cell(data.case.title || data.case.id)}`, '', banner(data), '',
    `Only blocking dependencies are listed. ${data.opportunities.length} opportunit${data.opportunities.length === 1 ? 'y' : 'ies'} across ${data.accounts.length} account(s).`, '',
    '## By owner role', '', ...sections,
    '## Case-level facts that block a live action', '',
    unknowns.length
      ? ['| Missing fact | Needed before |', '|---|---|', ...unknowns.map(fact => `| ${cell(fact.statement)} | ${cell(fact.needed_for)} |`)].join('\n')
      : 'None recorded.',
    '', '## Labelled scenarios used for workflow rehearsal', '',
    (data.scenarios || []).length
      ? (data.scenarios || []).map(scenario => `- **${cell(scenario.name || scenario.id)}** — ${cell(scenario.notice)}`).join('\n')
      : 'None recorded.', ''
  ].join('\n');
}

function crmStaging(data) {
  const header = ['crm_object', 'record_id', 'account_id', 'name', 'role', 'email', ...V.CRM_CUSTOM_FIELDS.map(f => f.toLowerCase().replace(/ /g, '_'))];
  const blockedHeader = ['crm_object', 'record_id', 'name', 'hold_reason'];
  const staged = [header];
  const blocked = [blockedHeader];
  const byId = new Map(data.sources.map(source => [source.id, source]));
  const locators = ids => (ids || []).map(id => (byId.get(id) || {}).locator).filter(Boolean).join('; ');
  const checked = ids => (ids || []).map(id => (byId.get(id) || {}).checked_on).filter(Boolean).sort().pop() || '';
  const illustrative = data.case.illustrative === true;
  for (const contact of data.contacts || []) {
    const reason = illustrative ? 'Illustrative case: synthetic records never reach a CRM or a marketing list.'
      : contact.crm_ready === true ? null
      : `Held in local staging: permission_to_contact "${contact.permission_to_contact || 'unknown'}"${contact.published === true ? '' : '; contact not published on a primary page'}.`;
    if (reason) blocked.push(['Contact', contact.id, contact.name, reason]);
    else staged.push(['Contact', contact.id, contact.account_id, contact.name, contact.role || '', contact.email || '',
      locators(contact.source_ids), (V.EVIDENCE_TIERS[contact.tier] || {}).label || '', checked(contact.source_ids)]);
  }
  for (const account of data.accounts) {
    const reason = illustrative ? 'Illustrative case: synthetic records never reach a CRM or a marketing list.'
      : (data.contacts || []).some(contact => contact.account_id === account.id && contact.crm_ready === true) ? null
      : 'No CRM-ready contact on this account; research stays in local staging.';
    if (reason) blocked.push(['Account', account.id, account.name, reason]);
    else staged.push(['Account', account.id, '', account.name, account.type || '', '',
      locators(account.source_ids), (V.EVIDENCE_TIERS[account.tier] || {}).label || '', checked(account.source_ids)]);
  }
  for (const opportunity of data.opportunities) {
    blocked.push(['Deal', opportunity.id, opportunity.name || opportunity.id,
      illustrative ? 'Illustrative case: synthetic records never reach a CRM or a marketing list.'
        : 'Deals are exported once the account has a CRM-ready contact and a real commercial basis.']);
  }
  return { staged: csv(staged), blocked: csv(blocked) };
}

function walkthrough(data) {
  const rows = V.MOMENTS.map(spec => {
    const moment = data.walkthrough.find(m => m.number === spec.number) || {};
    const state = moment.ready === true ? 'Ready' : 'Gap';
    return `| ${spec.number} | ${cell(spec.label)} | ${cell(spec.expects)} | ${state} | ${cell((moment.artifacts || []).join('; ') || '—')} | ${cell(moment.note || moment.gap || '')} |`;
  });
  return [
    `# Stage 5 — Walkthrough readiness: ${cell(data.case.title || data.case.id)}`, '', banner(data), '',
    'Each moment names the artifact a reviewer actually opens. A moment is "Ready" only when that artifact exists in the repository.', '',
    '| Moment | What the reviewer does | What it expects | State | Artifact | Note |', '|---|---|---|---|---|---|', ...rows, '',
    '## Engineering loop', '',
    'Sketch → inspect → build one increment → verify → revise. Record what was verified, what stays illustrative, and the next smallest useful improvement.', ''
  ].join('\n');
}

function renderCase(data, options = {}) {
  const findings = validateCase(data, options);
  const errors = errorsIn(findings);
  const files = new Map([['00-governance-report.md', governanceReport(data, findings)]]);
  if (errors.length) return { files, findings, errors };
  const crm = crmStaging(data);
  files.set('01-fact-spine.md', factSpine(data));
  files.set('02-research-staging.csv', researchStaging(data));
  files.set('03-action-brief.md', actionBrief(data));
  files.set('04-crm-staging.csv', crm.staged);
  files.set('04-crm-blocked.csv', crm.blocked);
  files.set('05-walkthrough.md', walkthrough(data));
  return { files, findings, errors };
}

function outputDir(data) {
  return path.join(outRoot, data.case.id);
}

function writeCase(data, options = {}) {
  const result = renderCase(data, options);
  const dir = outputDir(data);
  fs.mkdirSync(dir, { recursive: true });
  for (const [name, content] of result.files) fs.writeFileSync(path.join(dir, name), content);
  return { ...result, dir: path.relative(repoRoot, dir) };
}

function checkCase(data, options = {}) {
  const result = renderCase(data, options);
  const dir = outputDir(data);
  const stale = [];
  for (const [name, content] of result.files) {
    const target = path.join(dir, name);
    if (!fs.existsSync(target) || fs.readFileSync(target, 'utf8') !== content) stale.push(name);
  }
  return { ...result, stale, dir: path.relative(repoRoot, dir) };
}

module.exports = { renderCase, writeCase, checkCase, outputDir, outRoot, blockersFor, csv, csvCell };
